CC = gcc
S1= ./1/main.c ./1/hash.c
S2= ./2/main.c ./2/hash.c
S3= ./3/main.c ./3/heap.c
S4= ./4/main.c ./4/heap.c

all: q1 q2 q3 q4

q1:
	$(CC) $(S1) -o ./1/q1.o
q2:
	$(CC) $(S2) -o ./2/q2.o
q3:
	$(CC) $(S3) -o ./3/q3.o
q4:
	$(CC) $(S4) -o ./4/q4.o